docs: full docs for use-count-down hook
vintach/core pull request #46
Opened 2023-08-25 01:07 UTC by realDiegoR

Wrote down the documentation for the new hook useCountDown 💯

2023-08-25 17:23 UTC, immois commented on apps/raddix/data/docs/utilities/use-count-down/use-count-down.en.mdx
> +yarn add @raddix/useCountDown
The package name is incorrect as in the spanish version. The package name in npm is @raddix/use-count-down

2023-08-25 17:40 UTC, immois requested changes

2023-08-25 17:40 UTC, immois commented on apps/raddix/examples/use-count-down/example1.tsx
The example is good to demonstrate the functionality of `onFinished`, but it doesn't get to demonstrate the other functionalities that the hook has. I think a simple example of a timer would be better. What do you think?

2023-08-25 17:40 UTC, immois commented on apps/raddix/data/docs/utilities/use-count-down/use-count-down.es.mdx
> +      type: 'número'
I think that the type of value should also go in english since that is how it also goes in the language of JS or TS

2023-08-25 19:32 UTC, realDiegoR commented on apps/raddix/examples/use-count-down/example1.tsx
I like the idea. After a while I noticed that the example doesn't cover any of the action methods. Do you feel like removing this example entirely or rather have it as an `example2.ts` file?

2023-08-25 20:16 UTC, immois commented on apps/raddix/examples/use-count-down/example1.tsx
Yes, I'm fine with passing it as a second example

2023-08-26 01:18 UTC, immois approved these changes
Well done @realDiegoR, it's excellent 🚀

2023-08-26 02:24 UTC, merged